Hanodale.WebUI/Controllers/BusinessMasterController.cs
using Hanodale.BusinessLogic;
using Hanodale.WebUI.Authentication;
using Hanodale.WebUI.Helpers;
using Hanodale.WebUI.Models;
using Microsoft.Practices.ServiceLocation;
using System.ServiceModel;
using System.Web.Mvc;
using System.Linq;
using Hanodale.Utility.Globalize;
using Hanodale.WebUI.Logging.Elmah;
using System;
using Hanodale.Domain.DTOs;
using System.Collections.Generic;
using System.Web.Configuration;


namespace Hanodale.WebUI.Controllers
{
    [Authorize]
    public partial class BusinessMasterController : AuthorizedController
    {
        #region Declaration
        const string PAGE_URL = "BusinessMaster/Index";
        #endregion

        #region Constructor

        private readonly IBusinessService svc; 
        private readonly ICommonService svcCommon;
        private readonly IUserService svcUser;
        private readonly IWorkCategoryService svcWorkCategory;
        private readonly IBusinessClassificationService svcBusinessClassification;

        public BusinessMasterController(IBusinessService _bLService, ICommonService _commonService
            , IUserService _userService
            , IWorkCategoryService _workCategoryService
            , IBusinessClassificationService _businessClassificationService)
        {
            this.svc = _bLService; 
            this.svcCommon = _commonService;
            this.svcUser = _userService;
            this.svcWorkCategory = _workCategoryService;
            this.svcBusinessClassification = _businessClassificationService;
        }
        #endregion

        #region Business Details

        [AppAuthorize]
        public virtual ActionResult Index()
        {
            try
            {
                AccessRightsModel _accessRight = new AccessRightsModel();
                _accessRight = Common.GetUserRights(this.CurrentUserId, PAGE_URL);
                _accessRight.pageId = 0;
                if (_accessRight != null)
                {
                    if (_accessRight.canView)
                    {
                        return Json(new
                        {
                            viewMarkup = Common.RenderPartialViewToString(this, MVC.BusinessMaster.Views.Index, _accessRight)
                        });
                    }
                    else
                    {
                        return Json(new
                        {
                            status = Common.Status.Denied.ToString(),
                            message = Resources.NO_ACCESS_RIGHTS_VIEW
                        });
                    }
                }
                else
                {
                    return Json(new
                    {
                        status = Common.Status.Denied.ToString(),
                        message = Resources.NO_ACCESS_RIGHTS
                    });
                }
            }
            catch (Exception err)
            {
                throw new ErrorException(err.Message);
            }
        }


        [Authorize]
        public virtual ActionResult BindBusinessMaster(DataTableModel param)
        {
            int totalRecordCount = 0;
            IEnumerable<Businesses> filteredBusiness = null;
            try
            {
                AccessRightsModel _accessRight = new AccessRightsModel();
                _accessRight = Common.GetUserRights(this.CurrentUserId, PAGE_URL);

                if (_accessRight != null)
                {
                    if (_accessRight.canView || _accessRight.canEdit)
                    {
                        // Get login user Id
                        int userId = this.CurrentUserId;


                        Businesses filterModel = null;
                        string idFilter0 = Convert.ToString(Request["sSearch_0"]);
                        var idFilter1 = Convert.ToString(Request["sSearch_1"]);
                        var idFilter2 = Convert.ToString(Request["sSearch_2"]);
                        var idFilter3 = Convert.ToString(Request["sSearch_3"]);
                        var bus_Id = -1;

                        int.TryParse(idFilter2, out bus_Id);
                        filterModel = new Businesses();
                        filterModel.supplierBusinessType_Id = Convert.ToInt32(WebConfigurationManager.AppSettings["SupplierBusinessType"]);


                        if (!string.IsNullOrEmpty(idFilter0) || !string.IsNullOrEmpty(idFilter1) || !string.IsNullOrEmpty(idFilter2) || bus_Id > 0 || !string.IsNullOrEmpty(idFilter3))
                        {
                            
                            if (!string.IsNullOrEmpty(idFilter0))
                                filterModel.code = idFilter0;
                            if (!string.IsNullOrEmpty(idFilter1))
                                filterModel.name = idFilter1;
                            if (!string.IsNullOrEmpty(idFilter2) && bus_Id > 0)
                                filterModel.businessType_Id = Convert.ToInt32(idFilter2);
                            if (!string.IsNullOrEmpty(idFilter3))
                                filterModel.isActive = (idFilter3 ?? "") == "InActive" ? false : true;
                        }

                        var businessModel = this.svc.GetBusinessMaster(this.CurrentUserId, this.SubCostCenter, param.iDisplayStart, param.iDisplayLength, param.sSearch, filterModel);

                        if (svc != null)
                        {
                            //BusinessViewModel _businessViewModel = new BusinessViewModel();

                            //Sorting
                            var sortColumnIndex = param.iSortCol_0;
                            Func<Businesses, string> orderingFunction = (c => sortColumnIndex == 0 ? c.businessTypeName :
                                                            sortColumnIndex == 1 ? c.code :
                                                            sortColumnIndex == 2 ? c.name :
                                                            sortColumnIndex == 3 ? c.primaryContact :
                                                            sortColumnIndex == 4 ? c.phone : c.primaryEmail
                                                            );

                            filteredBusiness = businessModel.lstBusiness;
                            if (param.sSortDir_0 != null)
                            {
                                if (param.sSortDir_0 == "asc")
                                    filteredBusiness = filteredBusiness.OrderBy(orderingFunction);
                                else
                                    filteredBusiness = filteredBusiness.OrderByDescending(orderingFunction);
                            }

                            var result = BusinessData(filteredBusiness, this.CurrentUserId);
                            return Json(new
                            {
                                sEcho = param.sEcho,
                                iTotalRecords = businessModel.recordDetails.totalRecords,
                                iTotalDisplayRecords = businessModel.recordDetails.totalDisplayRecords,
                                aaData = result
                            }, JsonRequestBehavior.AllowGet);
                        }
                        else
                        {
                            return Json(new
                            {
                                status = Common.Status.Error.ToString(),
                                message = Resources.MSG_ERR_SERVICE
                            });
                        }
                    }
                    else
                    {
                        return Json(new
                        {
                            status = Common.Status.Denied.ToString(),
                            message = Resources.NO_ACCESS_RIGHTS_EDIT
                        });
                    }
                }
                else
                {
                    return Json(new
                    {
                        status = Common.Status.Denied.ToString(),
                        message = Resources.NO_ACCESS_RIGHTS
                    });
                }
            }
            catch (Exception err)
            {
                throw new ErrorException(err.Message);
            }
        }

        /// <summary>
        /// This method is to get the user data as string array to bind into datatbale
        /// </summary>
        /// <param name="userEntry">User list</param>
        /// <returns></returns>
        public List<string[]> BusinessData(IEnumerable<Businesses> businessEntry, int currentUserId)
        {
            return businessEntry.Select(entry => new string[]
            {  
                entry.businessTypeName,
                entry.code, 
                entry.name,
                entry.primaryContact,
                entry.phone,
                entry.primaryEmail,
                Common.Encrypt(currentUserId.ToString(), entry.id.ToString()),
                 GetUserRights(currentUserId,entry),
                (entry.statusColor==0?("Empty"):(entry.statusColor==1? ("LoginExist"):("LoginInActive")))
            }).ToList();
        }

        public string GetUserRights(int userId, Businesses _businessEn)
        {


            var objuser = svcUser.GetUserById(userId, userId);
            if (objuser.userRole_Id == Convert.ToInt32(WebConfigurationManager.AppSettings["SupplierRole"]))
            {
                return "3";
            }
            else
            {
                return "1";
            }
        }

        [Authorize]
        [HttpPost]
        public virtual JsonResult RenderAction()
        {

            AccessRightsModel _accessRight = new AccessRightsModel();
            try
            {
                _accessRight = Common.GetUserRights(this.CurrentUserId, PAGE_URL);

                return Json(new
                {

Hanodale.WebUI/Views/BusinessMaster/Index.cshtml
@model Hanodale.WebUI.Models.AccessRightsModel
@using Hanodale.Utility.Globalize
@using Hanodale.WebUI
@using System.Web.Optimization

@{
    ViewBag.Title = "Index";
    Layout = null;
}


<!-- Hidden Variable -->
<input type="hidden" id="alert-delete" value ="@Resources.MSG_CONFIRM_DELETE">
<input type="hidden" id="alert-reset" value ="@Resources.MSG_RESET_PASSWORD_CONFIRM">
<input type="hidden" class="mainPart" value="businessmaster">
<input type="hidden" class="table-congif" value="businessmaster" data-columncount="7" data-button="true" data-condition="true" data-conditionid="12" data-extended-event-btn="true" data-hidebtn="true" data-auto-hide-column="true" data-export-btn="true">
<input type="hidden" id="elementId" value="@Model.elementId" />
<!-- Hidden Variable -->

<!-- /.page-content -->
<div class="row-flex">
    <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
        <h1 class="page-title txt-color-blueDark">
            <i class="fa fa-table fa-fw "></i>@Resources.PAGE_HEADER_MANAGE_BUSINESS
        </h1>
    </div>
    @* @if (@Model.canAdd && !Model.readOnly)
    {
        <div class="col-xs-12 col-sm-5 col-md-5 col-lg-8">
            <ul id="sparks" class="">
                <li class="sparks-info">
                    <button id="create-business" data-url="Business/Create" class="btn btn-sm btn-primary" type="button">
                        <i class="fa fa-plus"></i>
                        @Resources.BTN_CREATE_BUSINESS
                    </button>
                </li>
            </ul>
        </div>
    }*@
</div>
<div id="message" class="alert alert-success" style="display: none"></div>
<!-- widget grid -->
<section id="widget-grid" class="">
    <!-- row -->
    <div class="row">
        @Html.Action("GetCustomSearchPanel", "BusinessMaster", new { searchType = @Model.pageId })
        <!-- NEW WIDGET START -->
        <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

            <!-- Widget ID (each widget will need unique ID)-->
            <div class="jarviswidget jarviswidget-color-darken" id="wid-id-0"
                data-widget-editbutton="false"
                data-widget-deletebutton="false"
                data-widget-colorbutton="false"
                data-widget-sortable="false">
                <header>
                    <span class="widget-icon"><i class="fa fa-table"></i></span>
                    <h2>@Resources.BUSINESS_GRID_TITLE </h2>

                </header>

                <!-- widget div-->
                <div>
                    <!-- widget edit box -->
                    <div class="jarviswidget-editbox">
                        <!-- This area used as dropdown edit box -->
                    </div>
                    <!-- end widget edit box -->

                    <!-- widget content -->
                    <div class="widget-body no-padding">
                        <fieldset class="scheduler-border">
                            <br />
                            <div class="control-group">
                                <span style='color: #05B32E' class="fa fa-square fa-lg"></span>
                                <label class="control-label input-label" for="Login Exist">Login Exist</label>

                                <span style='color: #404040; margin-left: 1em' class="fa fa-square fa-lg"></span>
                                <label class="control-label input-label" for="Login Not Exist">Login Not Exist</label>

                                <span style='color: #F93509; margin-left: 1em' class="fa fa-square fa-lg"></span>
                                <label class="control-label input-label" for="Login In-Active">Login In-Active</label>
                            </div>
                        </fieldset>
                        <table id="dt_businessmaster" class="table table-striped table-bordered table-hover" width="100%">
                            <thead>
                                <tr>
                                    <th data-class="expand"><i class="fa fa-fw fa-pencil text-muted hidden-md hidden-sm hidden-xs tableIcon"></i>@Resources.BUSINESS_BUSINESS_TYPE</th>
                                    <th data-hide="phone,tablet"><i class="fa fa-fw fa-qrcode text-muted hidden-md hidden-sm hidden-xs tableIcon"></i>@Resources.BUSINESS_CODE</th>
                                    <th data-hide="phone,tablet"><i class="fa fa-fw fa-pencil text-muted hidden-md hidden-sm hidden-xs tableIcon"></i>@Resources.BUSINESS_NAME</th>
                                    <th data-hide="phone,tablet"><i class="fa fa-fw fa-user text-muted hidden-md hidden-sm hidden-xs tableIcon"></i>@Resources.BUSINESS_PRIMARY_CONTACTS</th>
                                    <th data-hide="phone,tablet"><i class="fa fa-fw fa-phone text-muted hidden-md hidden-sm hidden-xs tableIcon"></i>@Resources.BUSINESS_PHONES</th>
                                    <th data-hide="phone,tablet"><i class="fa fa-fw fa-envelope-o text-muted hidden-md hidden-sm hidden-xs tableIcon"></i>@Resources.BUSINESS_PRIMARY_EMAIL</th>
                                    <th class="table-column-header" style="width: 100px;"></th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>

                    </div>
                </div>
            </div>
        </article>
    </div>

</section>


<!-- /.page-content -->

<!-- Protected Script -->

@Scripts.Render(bundles.scripts.common_index)

<!-- Protected Script -->
<script>
    _initActionExtended = function (partName, readOnly) {
        $('.LoginExist').closest('tr').children('td').css('color', '#05B32E')
        $('.LoginInActive').closest('tr').children('td').css('color', '#F93509')
        $('.Empty').closest('tr').children('td').css('color', '#404040')

    }
    $('#businessType_Id').change(function () {
        var businessType_Id = $('#businessType_Id').val();
        $('#business_Ids').each(function () {
            $(this).select2('val', '')
        });
    })
</script>

Hanodale.WebUI/Views/BusinessMaster/RenderAction.cshtml
@model Hanodale.WebUI.Models.AccessRightsModel
@using Hanodale.Utility.Globalize
@{
    Layout = null;
}

@if (Model.canView)
{
    <span class="edit-businessmaster btn btn-ribbon " data-url="BUSINESSMASTER_ID" data-placement="bottom" data-rel="tooltip" title="View" data-container="body">
        <i class="fa fa-eye"></i>
    </span>
}

Hanodale.WebUI/Views/BusinessMaster/_SearchPanel.cshtml
@model Hanodale.WebUI.Models.BusinessModel
@using Hanodale.Utility.Globalize
@using Hanodale.WebUI
@using System.Web.Optimization

@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "validation-form", @class = "form-horizontal searchPanel", autocomplete = "off" }))
{
   
    <article class="col-sm-12 col-md-12 col-lg-12 sortable-grid ui-sortable nPadding">

        <!-- Widget ID (each widget will need unique ID)-->

        <!-- end widget -->

        <div class="jarviswidget jarviswidget-sortable" id="wid-id-110" data-widget-colorbutton="false" data-widget-editbutton="false" data-widget-custombutton="false" style="padding: 0px 10px;" role="widget">
            <!-- widget options:
				usage: <div class="jarviswidget" id="wid-id-2" data-widget-editbutton="false">

				data-widget-colorbutton="false"
				data-widget-editbutton="false"
				data-widget-togglebutton="false"
				data-widget-deletebutton="false"
				data-widget-fullscreenbutton="false"
				data-widget-custombutton="false"
				data-widget-collapsed="true"
				data-widget-sortable="false"

				-->

            <header role="heading">
                <div class="jarviswidget-ctrls" role="menu"><a href="javascript:void(0);" class="button-icon jarviswidget-toggle-btn" rel="tooltip" title="" data-placement="bottom" data-original-title="Collapse"><i class="fa fa-minus "></i></a><a href="javascript:void(0);" class="button-icon jarviswidget-fullscreen-btn" rel="tooltip" title="" data-placement="bottom" data-original-title="Fullscreen"><i class="fa fa-expand "></i></a></div>
                <div class="widget-toolbar" role="menu">
                    <a data-toggle="dropdown" class="dropdown-toggle1 color-box selector" href="javascript:void(0);"></a>
                    <ul class="dropdown-menu dropdown-menu-right arrow-box-up-right color-select pull-right">
                        <li><span class="bg-color-green" data-widget-setstyle="jarviswidget-color-green" rel="tooltip" data-placement="left" data-original-title="Green Grass"></span></li>
                        <li><span class="bg-color-greenDark" data-widget-setstyle="jarviswidget-color-greenDark" rel="tooltip" data-placement="top" data-original-title="Dark Green"></span></li>
                        <li><span class="bg-color-greenLight" data-widget-setstyle="jarviswidget-color-greenLight" rel="tooltip" data-placement="top" data-original-title="Light Green"></span></li>
                        <li><span class="bg-color-purple" data-widget-setstyle="jarviswidget-color-purple" rel="tooltip" data-placement="top" data-original-title="Purple"></span></li>
                        <li><span class="bg-color-magenta" data-widget-setstyle="jarviswidget-color-magenta" rel="tooltip" data-placement="top" data-original-title="Magenta"></span></li>
                        <li><span class="bg-color-pink" data-widget-setstyle="jarviswidget-color-pink" rel="tooltip" data-placement="right" data-original-title="Pink"></span></li>
                        <li><span class="bg-color-pinkDark" data-widget-setstyle="jarviswidget-color-pinkDark" rel="tooltip" data-placement="left" data-original-title="Fade Pink"></span></li>
                        <li><span class="bg-color-blueLight" data-widget-setstyle="jarviswidget-color-blueLight" rel="tooltip" data-placement="top" data-original-title="Light Blue"></span></li>
                        <li><span class="bg-color-teal" data-widget-setstyle="jarviswidget-color-teal" rel="tooltip" data-placement="top" data-original-title="Teal"></span></li>
                        <li><span class="bg-color-blue" data-widget-setstyle="jarviswidget-color-blue" rel="tooltip" data-placement="top" data-original-title="Ocean Blue"></span></li>
                        <li><span class="bg-color-blueDark" data-widget-setstyle="jarviswidget-color-blueDark" rel="tooltip" data-placement="top" data-original-title="Night Sky"></span></li>
                        <li><span class="bg-color-darken" data-widget-setstyle="jarviswidget-color-darken" rel="tooltip" data-placement="right" data-original-title="Night"></span></li>
                        <li><span class="bg-color-yellow" data-widget-setstyle="jarviswidget-color-yellow" rel="tooltip" data-placement="left" data-original-title="Day Light"></span></li>
                        <li><span class="bg-color-orange" data-widget-setstyle="jarviswidget-color-orange" rel="tooltip" data-placement="bottom" data-original-title="Orange"></span></li>
                        <li><span class="bg-color-orangeDark" data-widget-setstyle="jarviswidget-color-orangeDark" rel="tooltip" data-placement="bottom" data-original-title="Dark Orange"></span></li>
                        <li><span class="bg-color-red" data-widget-setstyle="jarviswidget-color-red" rel="tooltip" data-placement="bottom" data-original-title="Red Rose"></span></li>
                        <li><span class="bg-color-redLight" data-widget-setstyle="jarviswidget-color-redLight" rel="tooltip" data-placement="bottom" data-original-title="Light Red"></span></li>
                        <li><span class="bg-color-white" data-widget-setstyle="jarviswidget-color-white" rel="tooltip" data-placement="right" data-original-title="Purity"></span></li>
                        <li><a href="javascript:void(0);" class="jarviswidget-remove-colors" data-widget-setstyle="" rel="tooltip" data-placement="bottom" data-original-title="Reset widget color to default">Remove</a></li>
                    </ul>
                </div>
                <span class="widget-icon"><i class="fa fa-edit"></i></span>
                <h2>Search Panel </h2>
                <span class="jarviswidget-loader"><i class="fa fa-refresh fa-spin"></i></span>
            </header>

            <!-- widget div-->
            <div role="content">

                <!-- widget edit box -->
                <div class="jarviswidget-editbox">
                    <!-- This area used as dropdown edit box -->

                </div>
                <!-- end widget edit box -->

                <!-- widget content -->
                <div class="widget-body no-padding">


                    <fieldset>
                        <div class="smart-form">
                            @*<legend>@Resources.PAGE_HEADER_CREATE_USER</legend>*@

                            <div class="form-group">
                                @Html.LabelFor(model => model.code, new { @class = "col-xs-12 col-sm-3 col-md-3 col-lg-2 control-label", })

                                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-5">
                                    @*@Html.LabelFor(model => model.firstName, new { @class = "", })*@
                                    <div class="clearfix">
                                        <label class="input">
                                            <i class="icon-append fa fa-pencil"></i>
                                            @Html.EditorFor(model => model.code, new { @class = "form-control no-required", @placeholder = @Html.DisplayNameFor(m => m.code) })

                                        </label>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.name, new { @class = "col-xs-12 col-sm-3 col-md-3 col-lg-2 control-label", })

                                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-5">
                                    @*@Html.LabelFor(model => model.lastName, new { @class = "", })*@
                                    <div class="clearfix">
                                        <label class="input">
                                            <i class="icon-append fa fa-pencil"></i>
                                            @Html.EditorFor(model => model.name, new { @class = "form-control no-required", @placeholder = @Html.DisplayNameFor(m => m.name) })
                                        </label>
                                    </div>
                                </div>
                            </div>
                            @if (@Model.searchType != 1)
                            {
                                <div class="form-group">
                                    @Html.LabelFor(model => model.businessType_Id, new { @class = "col-xs-12 col-sm-3 col-md-3 col-lg-2 control-label", })

                                    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-5">
                                        <div class="clearfix">
                                            <label class="select">
                                                @Html.EditorFor(model => model.businessType_Id, new { @class = "form-control multipleSelect no-required", dataValue = Model.BusinessTypes, setAll = true })
                                                @*<i></i>*@
                                            </label>
                                        </div>
                                    </div>
                                </div>
                                
                                          <div class="form-group">
                                    @Html.LabelFor(model => model.ActiveStatus, new { @class = "col-xs-12 col-sm-3 col-md-3 col-lg-2 control-label", })

                                    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-5">

                                        <div class="clearfix">
                                            <label class="select">
                                                @Html.EditorFor(model => model.ActiveStatus, new { @class = "form-control multipleSelect", dataValue = Model.lstStatus, setAll = false })
                                                @*<i></i>*@
                                            </label>
                                        </div>
                                    </div>  
                                </div>


                            }

                  
                        </div>
                    </fieldset>
                </div>
                <!-- end widget content -->
            </div>
            <!-- end widget div -->
        </div>
    </article>
}
@Scripts.Render(bundles.scripts.common_add_edit)